# conda env update --file environment.yml --prune
name: fin-ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - pip
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook  
  - plotly
  - ipykernel
  - requests
  - plotly
  - pip:
      - yfinance # Yahoo Finance API: For fetching historical market data, Financial Statements, financial news, Dividends and Splits and other stock-related information.
      - nselib # nselib has financial data and historical market data APIs for Python
      - nsepython # good library for returns computation etc
      - ta-lib
      - pandas_datareader
      - dhanhq
      - yahoofinancials # News and Headlines: Easy to find news articles and Headlines based on specific stocks and financial issues, which helps in sentiment analysis of the market.
      - pyarrow
      - fastparquet
      - duckdb
